"""Add hybrid yield prediction tree tables

Revision ID: add_hybrid_tree_tables
Revises: add_fertilizer_detection_tables
Create Date: 2025-11-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_hybrid_tree_tables'
down_revision: Union[str, None] = 'add_fertilizer_detection_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types if they don't exist
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fertilizertype') THEN
                CREATE TYPE fertilizertype AS ENUM ('organic', 'npk', 'urea', 'compost', 'none');
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'diseasestatus') THEN
                CREATE TYPE diseasestatus AS ENUM ('none', 'mild', 'severe');
            END IF;
        END $$;
    """)
    
    # Create trees table
    op.create_table('trees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plot_id', sa.Integer(), nullable=False),
        sa.Column('tree_code', sa.String(length=50), nullable=False),
        sa.Column('location_x', sa.Float(), nullable=True),
        sa.Column('location_y', sa.Float(), nullable=True),
        sa.Column('planting_date', sa.DateTime(), nullable=True),
        sa.Column('variety', sa.String(length=100), nullable=False),
        sa.Column('tree_age_years', sa.Float(), nullable=True),
        sa.Column('stem_count', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_harvest_date', sa.DateTime(), nullable=True),
        sa.Column('fertilizer_used', sa.Boolean(), nullable=False),
        sa.Column('fertilizer_type', sa.Enum('organic', 'npk', 'urea', 'compost', 'none', name='fertilizertype'), nullable=True),
        sa.Column('fertilizer_application_date', sa.DateTime(), nullable=True),
        sa.Column('disease_status', sa.Enum('none', 'mild', 'severe', name='diseasestatus'), nullable=False),
        sa.Column('disease_notes', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trees_plot_id'), 'trees', ['plot_id'], unique=False)
    
    # Create tree_measurements table
    op.create_table('tree_measurements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tree_id', sa.Integer(), nullable=False),
        sa.Column('measurement_date', sa.DateTime(), nullable=False),
        sa.Column('measured_by', sa.String(length=100), nullable=True),
        sa.Column('stem_diameter_mm', sa.Float(), nullable=False),
        sa.Column('num_existing_stems', sa.Integer(), nullable=False),
        sa.Column('stem_length_cm', sa.Float(), nullable=True),
        sa.Column('stem_thickness_variability', sa.Float(), nullable=True),
        sa.Column('canopy_coverage', sa.Float(), nullable=True),
        sa.Column('leaf_health_score', sa.Integer(), nullable=True),
        sa.Column('pest_damage', sa.Float(), nullable=True),
        sa.Column('soil_moisture', sa.Float(), nullable=True),
        sa.Column('rainfall_recent_mm', sa.Float(), nullable=True),
        sa.Column('temperature_recent_c', sa.Float(), nullable=True),
        sa.Column('actual_canes', sa.Integer(), nullable=True),
        sa.Column('actual_fresh_weight_kg', sa.Float(), nullable=True),
        sa.Column('actual_dry_weight_kg', sa.Float(), nullable=True),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('is_training_data', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_measurements_tree_id'), 'tree_measurements', ['tree_id'], unique=False)
    op.create_index(op.f('ix_tree_measurements_is_training_data'), 'tree_measurements', ['is_training_data'], unique=False)
    
    # Create tree_harvest_records table
    op.create_table('tree_harvest_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tree_id', sa.Integer(), nullable=False),
        sa.Column('harvest_date', sa.DateTime(), nullable=False),
        sa.Column('harvested_by', sa.String(length=100), nullable=True),
        sa.Column('canes_harvested', sa.Integer(), nullable=False),
        sa.Column('fresh_bark_weight_kg', sa.Float(), nullable=False),
        sa.Column('dry_bark_weight_kg', sa.Float(), nullable=True),
        sa.Column('bark_quality_grade', sa.String(length=20), nullable=True),
        sa.Column('stems_remaining', sa.Integer(), nullable=False),
        sa.Column('tree_health_after_harvest', sa.String(length=200), nullable=True),
        sa.Column('price_per_kg', sa.Float(), nullable=True),
        sa.Column('total_revenue', sa.Float(), nullable=True),
        sa.Column('notes', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_harvest_records_tree_id'), 'tree_harvest_records', ['tree_id'], unique=False)
    op.create_index(op.f('ix_tree_harvest_records_harvest_date'), 'tree_harvest_records', ['harvest_date'], unique=False)
    
    # Add new columns to plots table for hybrid model support
    op.add_column('plots', sa.Column('avg_stem_diameter_mm', sa.Float(), nullable=True))
    op.add_column('plots', sa.Column('min_stem_diameter_mm', sa.Float(), nullable=True))
    op.add_column('plots', sa.Column('max_stem_diameter_mm', sa.Float(), nullable=True))
    op.add_column('plots', sa.Column('diameter_variability', sa.Float(), nullable=True))
    op.add_column('plots', sa.Column('fertilizer_used_plot', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('plots', sa.Column('disease_present_plot', sa.String(length=20), nullable=True, server_default='none'))
    op.add_column('plots', sa.Column('tree_count', sa.Integer(), nullable=True))
    op.add_column('plots', sa.Column('trees_per_hectare', sa.Float(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove columns from plots table
    op.drop_column('plots', 'trees_per_hectare')
    op.drop_column('plots', 'tree_count')
    op.drop_column('plots', 'disease_present_plot')
    op.drop_column('plots', 'fertilizer_used_plot')
    op.drop_column('plots', 'diameter_variability')
    op.drop_column('plots', 'max_stem_diameter_mm')
    op.drop_column('plots', 'min_stem_diameter_mm')
    op.drop_column('plots', 'avg_stem_diameter_mm')
    
    # Drop tree tables
    op.drop_index(op.f('ix_tree_harvest_records_harvest_date'), table_name='tree_harvest_records')
    op.drop_index(op.f('ix_tree_harvest_records_tree_id'), table_name='tree_harvest_records')
    op.drop_table('tree_harvest_records')
    
    op.drop_index(op.f('ix_tree_measurements_is_training_data'), table_name='tree_measurements')
    op.drop_index(op.f('ix_tree_measurements_tree_id'), table_name='tree_measurements')
    op.drop_table('tree_measurements')
    
    op.drop_index(op.f('ix_trees_plot_id'), table_name='trees')
    op.drop_table('trees')
    
    # Drop enums if no other tables use them
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_name IN ('deficiency_analyses', 'fertilizer_recommendations')
            ) THEN
                DROP TYPE IF EXISTS diseasestatus;
                DROP TYPE IF EXISTS fertilizertype;
            END IF;
        END $$;
    """)
    
    # ### end Alembic commands ###