"""add_fertilizer_tables

Revision ID: f8e4cd409da0
Revises: 0ec2acc01c5a
Create Date: 2025-11-07 16:34:01.641407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e4cd409da0'
down_revision = '0ec2acc01c5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
