import os

# Roboflow settings
ROBOFLOW_API_KEY = os.getenv("ROBOFLOW_API_KEY", "YOUR_API_KEY")
ROBOFLOW_MODEL = os.getenv("ROBOFLOW_MODEL", "workspace/project_name/version")
CONF_THRESHOLD = float(os.getenv("CONF_THRESHOLD", 0.4))

# Pest disease detection settings
PEST_DISEASE_ROBOFLOW_API_KEY = os.getenv("PEST_DISEASE_ROBOFLOW_API_KEY")
PEST_DISEASE_ROBOFLOW_WORKSPACE = os.getenv("PEST_DISEASE_ROBOFLOW_WORKSPACE")
PEST_DISEASE_ROBOFLOW_WORKFLOW_ID = os.getenv("PEST_DISEASE_ROBOFLOW_WORKFLOW_ID")
PEST_DISEASE_ROBOFLOW_API_URL = os.getenv("PEST_DISEASE_ROBOFLOW_API_URL")
PEST_DISEASE_ROBOFLOW_USE_WORKFLOW = os.getenv("PEST_DISEASE_ROBOFLOW_USE_WORKFLOW") == "true"

# Cache settings
CACHE_ENABLED = True
CACHE_TTL = 3600  # seconds